"""create initial minirag schema

Revision ID: abc25a35ca49
Revises: 
Create Date: 2026-05-11 15:46:29.943264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc25a35ca49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=True),
    sa.Column('asset_pushed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_uuid'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_uuid', 'asset_name', name='uq_assets_project_uuid_asset_name')
    )
    op.create_index('ix_assets_project_uuid', 'assets', ['project_uuid'], unique=False)
    op.create_index('ix_assets_project_uuid_asset_type', 'assets', ['project_uuid', 'asset_type'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('chunk_order > 0', name='ck_chunks_chunk_order_positive'),
    sa.ForeignKeyConstraint(['asset_uuid'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_uuid'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_uuid', 'chunk_order', name='uq_chunks_asset_uuid_chunk_order')
    )
    op.create_index('ix_chunks_asset_uuid', 'chunks', ['asset_uuid'], unique=False)
    op.create_index('ix_chunks_project_uuid', 'chunks', ['project_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_project_uuid', table_name='chunks')
    op.drop_index('ix_chunks_asset_uuid', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_assets_project_uuid_asset_type', table_name='assets')
    op.drop_index('ix_assets_project_uuid', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
